### DISCUSSION TITLE
Asking Alexa to turn down the volume of a MEDIA_PLAYER with SmartIR should work?

### DISCUSSION THREAD

**Discussion by rafareusch** [litinoveweedle/SmartIR#201] [Q&A]
Hey guys, I'm running into an isue with HA/SmartIR that when I say to Alexa to lower/increase volume of my TV that is IR controlled via SmartIR, nothing happens.
If I say, Alexa, TV volume 20, then TV is set to 20 and then when I ask to turn the volume down, it lowers by 3 steps.

I see VolumeDown and Up commands are defined in the 1060.json.

When I use another entity (from the TV itself for example) or a simple Wi-Fi IR with Tuya App, they work as expected. Maybe it's an incompability of the export entity of HA?

Is this expected behavior?
Just want to make sure before opening a PR

Code:
HA 2024.2.4 (happens at least since 2023.12)
1.19.1

```
media_player:
  - platform: smartir
    name: Smartir TV sala
    unique_id: smartir_tvsala
    device_code: 1060
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.rm4new
      delay_secs: 0.5
      num_repeats: 1
```

Thanks!
