### ISSUE TITLE
"Invalid climate device JSON file '9998.json': invalid format at temperature level" after update to 1.18.0

### ISSUE THREAD

**Issue by phcella** [litinoveweedle/SmartIR#105]
**Home Assistant version:** 2024.8.1

**SmartIR version:** 1.18.0

**SmartIR configuration**

```yaml

climate:
  - platform: smartir
    name: Ar Condicionado
    unique_id: room_pedro_ac
    device_code: 9998
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.broadlink_rm4_pro_remote
    temperature_sensor: sensor.multi_sensor_pedro_temperature
    humidity_sensor: sensor.multi_sensor_pedro_humidity
    #power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Ar Condicionado Bia
    unique_id: room_bia_ac
    device_code: 9997
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.broadlink_rm4_mini
    temperature_sensor: sensor.multi_sensor_bia_temperature
    humidity_sensor: sensor.multi_sensor_bia_humidity
    #power_sensor: binary_sensor.ac_power

```

**Describe the bug**
After update SmartIR to 1.18.0, i got some problems that I fixed, but I can't how to fix this error:
`Invalid climate device JSON file '9998.json': invalid format at temperature level.`
`Invalid climate device JSON file '9997.json': invalid format at temperature level.`

**Expected behavior**
Smart IR start with no errors
 
**To Reproduce**
On start of Home Assistant

**Debug log**
Enable integration debug logging, reproduce the bug and attached log. Insert log formatted as a code to keep it readable. To enable debug logging, put into your HA configuration.yaml following lines and restart HA.

```yaml
2024-08-14 00:06:59.965 ERROR (MainThread) [custom_components.smartir] Invalid climate device JSON file '9998.json': invalid format at temperature level.
2024-08-14 00:06:59.966 ERROR (MainThread) [custom_components.smartir.climate] SmartIR climate device data init failed!
2024-08-14 00:06:59.992 ERROR (MainThread) [custom_components.smartir] Invalid climate device JSON file '9997.json': invalid format at temperature level.
2024-08-14 00:06:59.992 ERROR (MainThread) [custom_components.smartir.climate] SmartIR climate device data init failed!
```

**Additional context**
I uploaded the two custom codes that are in custom_components\smartir\custom_codes\climate

[9998.json](https://github.com/user-attachments/files/16607279/9998.json)
[9997.json](https://github.com/user-attachments/files/16607280/9997.json)
