### ISSUE TITLE
After upgrading to Home Assistant Operating System 13.0 - Invalid config

### ISSUE THREAD

**Issue by alexvaltchev** [litinoveweedle/SmartIR#106]
Invalid config
The following integrations and platforms could not be set up:

[smartir.climate](https://github.com/litinoveweedle/SmartIR)
**Home Assistant version**
2024.8.1

**SmartIR version**
1.18.0

![Screenshot_4](https://github.com/user-attachments/assets/30cd9d9b-903b-4c8f-8882-66d21f2c0c45)

**SmartIR configuration**

```
- platform: smartir
  name: Office AC
  unique_id: office_ac
  device_code: 1029
  controller_data: remote.office_remote
  temperature_sensor: sensor.office_temperature_sensor
  humidity_sensor: sensor.office_humidity_sensor

- platform: smartir
  name: Bedroom AC
  unique_id: bedroom_ac
  device_code: 1029
  controller_data: remote.bedroom_remote
  temperature_sensor: sensor.bedroom_temperature_sensor
  humidity_sensor: sensor.bedroom_humidity_sensor
```

**Describe the bug**
After upgrading to HAOS 13 I get -  Invalid config

![Screenshot_3](https://github.com/user-attachments/assets/c2f67f17-9c9e-4930-ba15-1603c3c9704f)

**Comment by litinoveweedle** [comment]
Read release notes, change configuration according to the documentation.

**Comment by alexvaltchev** [comment]
@litinoveweedle I noticed there is new configuration process but I dont understand what to do. Can you help for newbies like me to fix it. Can you please give simple step by step guide on how to fix the issue. I am trying to undeerstand this here - https://github.com/litinoveweedle/SmartIR/blob/1.18.0/docs/README.md#platform-setup-instructions but I am unable to do so. Sorry :(

**Comment by litinoveweedle** [comment]
Look here for the snippets of the configuration:

https://github.com/litinoveweedle/SmartIR/blob/1.18.0/docs%2FCLIMATE.md

Sorry, I am not able to provide you end user support.

**Comment by alexvaltchev** [comment]
OK I did it according to THIS here and it worked. :) Thank you.

Only 2 questions.

Why need delay? And why need repeat?

```
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1000
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.bedroom_remote
      delay_secs: 0.5
      num_repeats: 3
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
```
