### ISSUE TITLE
Error while setting up smartir platform for climate

### ISSUE THREAD

**Issue by stakost** [litinoveweedle/SmartIR#119]
I’m trying to launch the integration in HA, but every call results in an error. What am I doing wrong?
HA Version: 2024.7.4

```
- platform: smartir
  name: test AC
  unique_id: test_ac_remote
  device_code: 1065
  controller_data:
    controller_type: UFOR11
    mqtt_topic: zigbee2mqtt/0x8c65a3fffeba9175/set/ir_code_to_send
```

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/b786e8d7-a3be-4f8a-be5e-6875893e6960">
