### ISSUE TITLE
media_player doesn't send off IR command if entity is off but TV is on

### ISSUE THREAD

**Issue by rafareusch** [litinoveweedle/SmartIR#156]
**I'm having a issue with the debug logs and will update this post with relevant logs and yaml shortly**

**Home Assistant version**
2024.11.2

**SmartIR version**
1.19.0

**SmartIR configuration**

```yaml

media_player:
  - platform: smartir
    name: Smartir TV sala
    unique_id: smartir_tvsala
    device_code: 1060
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.rm4new
      delay_secs: 0.5
      num_repeats: 1

```

**Describe the bug**
AFTER 1.17.15, if the TV is ON but the TV media player entity is OFF (turned on via real remote). HA wont turn TV off using the media_player.turn_off service. The IR command is not sent

If I turn the entity ON, then OFF, the OFF IR command will be sent.
(either via UI or service)

**Expected behavior**
To HA always send the IR turn off command independently to the entity state (climate entity works exactly like that!)
(works this way before 1.17.15)

**To Reproduce**
1. Turn on TV manually 
2. send media_player.turn_off command to the corresponding TV entity 

**Debug log**
(it's the only log related to smartir i see after reproducing the bug)
```yaml
2024-11-23 17:52:58.030 DEBUG (MainThread) [custom_components.smartir.media_player] Setting up the SmartIR media player platform
```

**Additional context**
I want to reinforce that the climate entity works exactly in the way described in Expected field. I was using the "official" SmartIR integration and never encountered this issue. I'm currently reinstalling it to check and will update this post with the information
