### ISSUE TITLE
SmartIR Platform Error - Requirements for smartir not found: ['aiofiles==0.6.0']

### ISSUE THREAD

**Issue by robchap79** [litinoveweedle/SmartIR#169]
**Home Assistant version**
Core 2024.12.5
Supervisor 2024.12.0
OS 14.1

**SmartIR version**
1.19.0

**SmartIR configuration**

```
media_player 10:
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 1000
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.livingroom_remote
      delay_secs: 0.5
      num_repeats: 3
    power_sensor: binary_sensor.living_room_tv_power
```

**Describe the bug**
Upon uninstalling the old SmartIR integration (which no longer works under the current version of HA), I have installed this fork of SmartIR (and I thank you for forking and maintining this), I get the following error when checking my config:-
Platform error 'media_player' from integration 'smartir' - Requirements for smartir not found: ['aiofiles==0.6.0']. 

I get the same error for climate integrations when I add them to the config, the devices show as unavailable on the dashboard.

**Debug log**

```
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 14:07:44 (3 occurrences)
Last logged: 14:07:45

Unable to install package aiofiles==0.6.0: × No solution found when resolving dependencies: ╰─▶ Because you require aiofiles==0.6.0 and aiofiles>=24.1.0, we can conclude that your requirements are unsatisfiable.
```
