### ISSUE TITLE
Duplicated commands detected in 1402.json

### ISSUE THREAD

**Issue by paoloantinori** [litinoveweedle/SmartIR#170]
**Home Assistant version**
`2024.12.5`

**SmartIR version**
`1.19.0`

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: Sala AC
    unique_id: ac_sala
    device_code: 1402
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.broadlink_remote
      delay_secs: 0.5
      num_repeats: 3
```

**Describe the bug**
Just a note in the logs that says the following
```
2024-12-28 17:41:22.744 INFO (MainThread) [custom_components.smartir] Invalid climate device JSON file '1402.json': duplicated commands detected.
```

**Expected behavior**
No log entries. And I wonder if that should be a Warning level anyway
 
**To Reproduce**
1. start HA, it's logged at boot

**Debug log**
see attached

[home-assistant_smartir_2024-12-28T16-50-53.852Z.log](https://github.com/user-attachments/files/18266862/home-assistant_smartir_2024-12-28T16-50-53.852Z.log)

**Comment by litinoveweedle** [comment]
Hello,

Climate JSON files should not contain the same commands. Please refer to the documentation what are the options. You can get rid of the warning if you modify the JSON file accordingly and I will accept PR of the modifications. This is exactly the reason for the warning - get the user attention and hope any similar file will be fixed. So this is not a bug, but a feature. :-)

**Comment by paoloantinori** [comment]
I can try helping but I don't get what are the specs of these JSON files.
For what I can see in https://github.com/litinoveweedle/SmartIR/blob/master/codes/climate/1402.json
there is this structure:

```yaml
  "commands": {
    "off": "JgAkAQABK...",
    "heat": {
      "low": {
        "swing": {
          "16": "JgAmAQA...",

```

which of those keys are considered commands? I would expect the keys under the `commands` entry.
And if that is the keys, there are no repetitions in the file, the only repetition I see in the files is down to those keys that are just numbers.

![image](https://github.com/user-attachments/assets/411e3bbe-3292-4de3-b575-a9538a979ed5)
