### ISSUE TITLE
Timer functionality

### ISSUE THREAD

**Issue by CoatsyJnr** [litinoveweedle/SmartIR#204]
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
Timer functionality. My aircon has built in timer on the remote to set the AC to power of anywhere from 1 to 12 hours. I'd love similar using Home Assistant's built in timer function but straight in SmartIR

### Describe alternatives you've considered
Currently have created a button and a timer, that when the button is pressed, turns the aircon on, sets the temperature and starts the timer. I also have another automation that turns off the AC unit when the timer becomes idle

### Additional context
Below are my 2 automations that I'm using, along with a bottom and a timer set to 1hr
**Aircon on 1hr**
```
alias: Aircon 1hr on
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_button.aircon_1hr
conditions: []
actions:
  - action: timer.start
    metadata: {}
    data: {}
    target:
      entity_id: timer.1hr
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 21
      hvac_mode: cool
    target:
      entity_id: climate.living_room_ac
  - action: fan.turn_on
    metadata: {}
    data:
      percentage: 66
    target:
      entity_id: fan.living_room_fans
mode: single
```
**Aircon Auto off** 
```
alias: Aircon Auto off
description: ""
triggers:
  - trigger: state
    entity_id:
      - timer.1hr
    from: active
    to: idle
conditions: []
actions:
  - action: climate.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: climate.living_room_ac
  - action: fan.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: fan.living_room_fans
mode: single
```
