### ISSUE TITLE
Climate Entity not working as expected

### ISSUE THREAD

**Issue by LZXCorp** [litinoveweedle/SmartIR#40]
**Home Assistant version**
2024.6.1

**SmartIR version**
v1.17.6

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: <some valid name>
    unique_id: <some valid UID>
    device_code: 1133
    controller_data: <some valid remote>
    power_sensor: <some valid input_boolean>
    power_sensor_restore_state: true
```

**Describe the bug**

When I use a service to turn on the `climate` device,

**EXPECTED:** The `input_boolean` also turns on
**BUG:** The `input_boolean` did not change state and remains in the `off` state.

Both turned on the physical climate device, but the `input_boolean` state itself did not change.

**Debug log**

```text
Can't find any logs at all
```

**Additional context**

After a few months of using `SmartIR`, it suddenly completely stopped working, so I went ahead and found this alternative fork and decided to use it.

I have removed the `smartir:` from the `configuration.yaml` file.
