### ISSUE TITLE
Code sent multiple times (Tuya ZS06)

### ISSUE THREAD

**Issue by leah-potato** [litinoveweedle/SmartIR#44]
**Home Assistant version**
- Core 2024.6.2
- Supervisor 2024.06.2
- Operating System 12.4
- Frontend 20240610.0

**SmartIR version**
- 1.17.16

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: Chill Room
    unique_id: chill_room_thermostat
    device_code: 1291
    controller_data: zigbee2mqtt/chill_room_ir/set/ir_code_to_send
```

**Describe the bug**
I've got an issue with a Tuya [ZS06](https://www.zigbee2mqtt.io/devices/ZS06.html#tuya-zs06) where the same command is being **repeated 8 times** in Zigbee2Mqtt. It also sometimes doesn't work at all (see logs below).

```
Info 2024-06-26 20:14:57MQTT publish: topic 'zigbee2mqtt/chill_room_ir', payload '{"last_seen":"2024-06-26T20:14:57+10:00","learn_ir_code":null,"learned_ir_code":"ESANSgbAAXsB7QF7AcABwgTAAeABB4ATQAdAF0ADAXsBQAMF7QF7AcABQA9AA0AL4AEDgBsBewHgAwOAE0ABAnsBwGAB4Ak3A8ABewGAJ0AH4AMfQAEDewHAAUAT4BMDQCNAA0AjQAeAAwPtAXsBwAvgAQdAI0ADgBOAI0ABAXsBgANAG8ADQAEBewGAI0ATAnsBwGABQAfgEQOALwF7AYADwDfAB0ABAXsB4AsjwBPAB4An4AU3AcABwA9AC0AD4AcPQAFAE0ABwB/gAw/AEwd7AcABwAHAAQ==","linkquality":58}'
```

If I simply and use a template switch, it works as expected with one code sent:

```yaml
switch:
  - platform: template
    switches:
      stretch_room_ac:
        turn_on:
          service: mqtt.publish
          data:
            payload: >- #Replace IR Code
              {"ir_code_to_send": "code here etc etc"}
            topic: zigbee2mqtt/chill_room_ir/set
```

**Debug log**

Zigbee2Mqtt
```yaml

Error 2024-06-26 20:54:29Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'data')}

```

```yaml
Logger: homeassistant.components.mqtt.sensor
Source: /usr/src/homeassistant/homeassistant/components/mqtt/sensor.py:265
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 20:38:50 (9 occurrences)
Last logged: 20:38:54

Invalid state message 'ESANSgbAAXsB7QF7AcABwgTAAeABB4ATQAdAF0ADAXsBQAMF7QF7AcABQA9AA0AL4AEDgBsBewHgAwOAE0ABAnsBwGAB4Ak3A8ABewGAJ0AH4AMfQAEDewHAAUAT4BMDQCNAA0AjQAeAAwPtAXsBwAvgAQdAI0ADgBOAI0ABAXsBgANAG8ADQAEBewGAI0ATAnsBwGABQAfgEQOALwF7AYADwDfAB0ABAXsB4AsjwBPAB4An4AU3AcABwA9AC0AD4AcPQAFAE0ABwB/gAw/AEwd7AcABwAHAAQ==' from 'zigbee2mqtt/chill_room_ir'Logger: homeassistant.components.mqtt.sensor
Source: /usr/src/homeassistant/homeassistant/components/mqtt/sensor.py:265
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 20:38:50 (9 occurrences)
Last logged: 20:38:54

Invalid state message 'ESANSgbAAXsB7QF7AcABwgTAAeABB4ATQAdAF0ADAXsBQAMF7QF7AcABQA9AA0AL4AEDgBsBewHgAwOAE0ABAnsBwGAB4Ak3A8ABewGAJ0AH4AMfQAEDewHAAUAT4BMDQCNAA0AjQAeAAwPtAXsBwAvgAQdAI0ADgBOAI0ABAXsBgANAG8ADQAEBewGAI0ATAnsBwGABQAfgEQOALwF7AYADwDfAB0ABAXsB4AsjwBPAB4An4AU3AcABwA9AC0AD4AcPQAFAE0ABwB/gAw/AEwd7AcABwAHAAQ==' from 'zigbee2mqtt/chill_room_ir'

```

```yaml
Logger: homeassistant.components.mqtt.sensor
Source: /usr/src/homeassistant/homeassistant/components/mqtt/util.py:268
integration: MQTT (documentation, issues)
First occurred: 20:38:50 (9 occurrences)
Last logged: 20:38:53

Cannot update state for entity sensor.chill_room_ir_learned_ir_code after processing payload on topic zigbee2mqtt/chill_room_ir. The requested state (292) exceeds the maximum allowed length (255). Fall back to unknown, failed state: ESANSgbAAXsB7QF7AcABwgTAAeABB4ATQAdAF0ADAXsBQAMF7QF7AcABQA9AA0AL4AEDgBsBewHgAwOAE0ABAnsBwGAB4Ak3A8ABewGAJ0AH4AMfQAEDewHAAUAT4BMDQCNAA0AjQAeAAwPtAXsBwAvgAQdAI0ADgBOAI0ABAXsBgANAG8ADQAEBewGAI0ATAnsBwGABQAfgEQOALwF7AYADwDfAB0ABAXsB4AsjwBPAB4An4AU3AcABwA9AC0AD4AcPQAFAE0ABwB/gAw/AEwd7AcABwAHAAQ==

```

**Additional context**
<img width="1164" alt="zigbee2mqtt" src="https://github.com/litinoveweedle/SmartIR/assets/128001814/bfabafec-ea2e-4c19-9175-c8353aca91a7">
<img width="469" alt="image" src="https://github.com/litinoveweedle/SmartIR/assets/128001814/bb72fe5c-c730-4c1f-ac74-0960d2a81ebf">

[1291.json](https://github.com/user-attachments/files/15986755/1291.json)

Probably something really simple but it's been doing my head in! Can't seem to find a similar issue on here or the original smartIR.
