### ISSUE TITLE
Add num_repeats like the Broadlink integration

### ISSUE THREAD

**Issue by kineticscreen** [litinoveweedle/SmartIR#56]
For whatever reason, I found that I've needed to repeat the remote sends 2 or 3 times to ensure 100% reliability when I first setup the Broadlink integration to control an AC. Would be great to have the same functionality in SmartIR now that I've moved across to it.

**Comment by litinoveweedle** [comment]
Hello, thank you for report. Although it would probably not be so difficult to add such feature I am not fully convinced, that  this is the right direction. I have a feeling, that instead of trying to fix the root cause of the issue, your proposal is just a hack. 

As SmartIR uses Broadlink integration (in your case) to send the codes, it is understandable, that if the Broadlink has issue, SmartIR have it as well. Did you created issue for Broadlink integration? Did you tried to get some more info about it, or collect other users reports - if they have similar problems?

**Comment by kineticscreen** [comment]
I think you've misunderstood. The Broadlink integration already has the "num_repeats" option when sending a remote message. For whatever reason, I found that having it repeat the signal twice using this made the operation of my AC 100% reliable (and no I don't know what it is, but placement of the the Broadlink unit wasn't enough). Otherwise the AC would fail to respond to a message maybe 10-20% of the time. Maybe the broadlink sends the signal at a shorter period than the AC samples? Who knows.
It may well be that it's a known issue that was investigated in the past and they found that creating the option to repeat the message was a sensible solution. I'm just offering that it might be worth implementing.

**Comment by litinoveweedle** [comment]
Oh sorry my fault, thank you for detailed explanation. So you would like to propagate `num_repeats` as documented [here](https://www.home-assistant.io/integrations/broadlink/) in the same way how `delay` is currently/already propagated.

Speaking about 'delay' this seems to be Broadlink controller specific as well, so my proposal would be to move it to `controller_data` as documented [here](https://github.com/litinoveweedle/SmartIR/blob/master/docs/CLIMATE.md) and add possibility to set `num_repeats` as well. What do you think about this proposal?

**Comment by kineticscreen** [comment]
So just to be clear, the example there could end up looking like this:

```
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1000
    controller_data: remote.bedroom_remote
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
    num_repeats: 2
```

That would be fine with me - though the only thing I note is that with the Broadlink integration, they have it as an option when calling individual command sends - not as a global setting for every command sent.

Again, this would be fine for me, and I would have set it as such for the Broadlink if I could have, but just putting it out there that there could be scenarios where someone might want only certain commands repeated, whereas repeating others could cause problems? I'm thinking volume changes or the like... but maybe it isn't relevant within the more limited commands of SmartIR. And of course they don't have to use it...

**Comment by litinoveweedle** [comment]
yep, or maybe something like this:

```
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1000
    controller_data: remote.bedroom_remote
    controller_params:
      - delay: 0.3
        num_repeats: 3
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
```
