### ISSUE TITLE
Error on latest beta with controller type MQTT and UFOR11

### ISSUE THREAD

**Issue by gurglingtonic** [litinoveweedle/SmartIR#98]
Tested the latest beta, this error appear at "Check Configuration":-

> Invalid config for 'smartir' from integration 'fan' at packages/configuration/fan.yaml, line 37: required key 'remote_entity' not provided
> Invalid config for 'smartir' from integration 'fan' at packages/configuration/fan.yaml, line 38: Values are not equal: value:UFOR11 != target:Broadlink for dictionary value 'controller_data->controller_type', got 'UFOR11'
> Invalid config for 'smartir' from integration 'fan' at packages/configuration/fan.yaml, line 39: 'mqtt_topic' is an invalid option for 'fan.smartir', check: controller_data->mqtt_topic

> Invalid config for 'smartir' from integration 'fan' at packages/configuration/fan.yaml, line 37: required key 'remote_entity' not provided
> Invalid config for 'smartir' from integration 'fan' at packages/configuration/fan.yaml, line 38: Values are not equal: value:MQTT != target:Broadlink for dictionary value 'controller_data->controller_type', got 'MQTT'
> Invalid config for 'smartir' from integration 'fan' at packages/configuration/fan.yaml, line 39: 'mqtt_topic' is an invalid option for 'fan.smartir', check: controller_data->mqtt_topic

My fan.yaml config:-
```
  - platform: smartir
    name: Ceiling Fan - Bedroom II
    unique_id: ceiling_fan_bedroom_2
    device_code: 16
    controller_data:
      controller_type: UFOR11
      mqtt_topic: zigbee2mqtt_lan/Bedroom 2 - IR Remote/set
    power_sensor: switch.bedroom_2_lights_fan_switch_left
    power_sensor_restore_state: true
```

```
  - platform: smartir
    name: Ceiling Fan - Bedroom II
    unique_id: ceiling_fan_bedroom_2
    device_code: 16
    controller_data:
      controller_type: MQTT
      mqtt_topic: zigbee2mqtt_lan/Bedroom 2 - IR Remote/set/ir_code_to_send
    power_sensor: switch.bedroom_2_lights_fan_switch_left
    power_sensor_restore_state: true
```

May need to update the checker for MQTT and UFOR11 or please advise otherwise.
